name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    # This is the default list, but I don't know how to YAML an empty pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache-dependency-path: package-lock.json

      - name: NPM install
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Check formatting
        run: bun run format:check

  tests-local:
    runs-on: ubuntu-latest
    env:
      WIREIT_LOGGER: quiet-ci
      WIREIT_PARALLEL: 1

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache-dependency-path: package-lock.json

      # - uses: google/wireit@setup-github-actions-caching/v2

      - name: Log Node and NPM versions
        run: node --version && npm --version
        
      - name: NPM install
        run: bun install --frozen-lockfile

      - name: Install playwright browsers
        run: bunx playwright install --with-deps

      - name: Build
        run: bun run build

      - name: Test
        env:
          BROWSERS: preset:local
          CONCURRENT_BROWSERS: 3
        run: bun run test

  windows-tools:
    runs-on: windows-latest
    env:
      WIREIT_LOGGER: quiet-ci
      WIREIT_PARALLEL: 1

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache-dependency-path: package-lock.json

      # - uses: google/wireit@setup-github-actions-caching/v2

      - name: NPM install
        run: bun install --frozen-lockfile

      - name: Install playwright browsers
        run: bunx playwright install --with-deps

      - name: Test
        env:
          RUN_BROWSER_TESTS: false
        run: bun run test:windows
